djangotut/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns(
    '',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^polls/', include('polls.urls', namespace="polls")),
)

polls/urls.py
from django.conf.urls import patterns, url

from . import views

urlpatterns = patterns(
    '',
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/results/$', views.ResultsView.as_view(),
        name='results'),
    url(r'^(?P<question_id>\d+)/vote/$', views.vote, name='vote'),
    url(r'^create/$', views.create_question, name='create')
)

polls/models.py
import datetime

from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polls/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.views import generic
from django.utils import timezone

from .models import Question
from .models import Choice


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """
        Return the last five published questions
        (excluding those in the future)
        """
        return Question.objects.filter(
            pub_date__lte=timezone.now()).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def vote(request, question_id):
    p = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = p.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': p,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(p.id,)))


def create_question(request):
    if (request.POST):
        try:
            q = Question(question_text=request.POST["question_text"],
                         pub_date=timezone.now())
            q.save()
            for i in range(1, 4):
                choice_text = request.POST['choice{}'.format(i)]
                c = Choice(question=q, choice_text=choice_text)
                c.save()
        except (KeyError):
            return render(request, 'polls/index.html')

        return HttpResponseRedirect(reverse('polls:detail', args=(q.id,)))
    else:
        return render(request, 'polls/create.html')

polls/templates/polls/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <title>{% block title %}Poll{% endblock %}</title>
  <link rel="stylesheet" href="{% static 'polls/css/bootstrap.min.css' %}" />
  <link rel="stylesheet" href="{% static 'polls/css/bootstrap-theme.min.css' %}" />
</head>

<body>
  {% block body_block %}{% endblock %}
</body>

</html>

polls/templates/polls/create.html
{% extends 'polls/base.html' %} {% block title %}Create a poll{% endblock %}{% block body_block %}

<div class="container">
  <h1>Create a poll</h1>
  <form action="{% url 'polls:create' %}" method="post">
    {% csrf_token %}
    <div class="form-group">
      <label>
        Question
        <input type="text" name="question_text" id="question_text">
      </label>
    </div>
    <div class="form-group">
      {% for count in "xxx" %}
      <label>
        Choice {{ forloop.counter }}
        <input type="text" name="choice{{ forloop.counter }}">
      </label>
      {% endfor %}
    </div>
    <input type="submit" class="form-control btn btn-default" value="Create">
  </form>
  <a href="{% url 'polls:index' %}">Return to polls.</a>
</div>
{% endblock %}

polls/templates/polls/detail.html
{% extends 'polls/base.html' %} {% block title %}Poll Details{% endblock %} {% block body_block %}

<div class="container">
  <h1>{{ question.question_text }} </h1> {% if error_message %}
  <p><strong>{{ error_message }}</strong></p>{% endif %}

  <form action="{% url 'polls:vote' question.id %}" method="post">
    <div class="form-group">
      {% csrf_token %}
      {% for choice in question.choice_set.all %}
      <div class="radio">
        <label>
          <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}"> {{ choice.choice_text }}
        </label>
      </div>
      <br/> {% endfor %}
    </div>
    <input type="submit" class="form-control" value="Vote">
  </form>
  <a href="{% url 'polls:index' %}">Return to polls</a>
</div>
{% endblock %}

polls/templates/polls/index.html
{% extends 'polls/base.html' %} {% block title %}Polls{% endblock %} {% block body_block %}
<div class="container">
  <h1>Polls</h1> {% if latest_question_list %}
  <ul>
    {% for question in latest_question_list %}
    <li>
      <a href="{% url 'polls:detail' question.id %}">
            {{ question.question_text }}
          </a>
    </li>
    {% endfor %}
  </ul>
  {% else %}
  <p>No polls are available.</p>
  {% endif %}
  <a href="{% url 'polls:create' %}">Create a poll.</a>
</div>
{% endblock %}

polls/templates/polls/results.html
{% extends 'polls/base.html' %} {% block title %}Poll Details{% endblock %} {% block body_block %}
<div class="container">
  <h1>{{ question.question_text }}</h1>
  <ul>
    {% for choice in question.choice_set.all %}
    <li>
      {{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}
    </li>
    {% endfor %}
    <a href="{% url 'polls:detail' question.id %}">Vote again?</a>
    <a href="{% url 'polls:index' %}">Go back to polls.</a>
</div>
{% endblock %}